import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt


def parse_args():
    parser = argparse.ArgumentParser(
        description="Create training curve visualizations from a history CSV."
    )
    parser.add_argument(
        "--history",
        type=Path,
        default=Path("outputs/training_history.csv"),
        help="Training history CSV generated by train.py."
    )
    parser.add_argument(
        "--output_dir",
        type=Path,
        default=Path("outputs/training_visualizations"),
        help="Folder for generated training visualizations."
    )
    parser.add_argument(
        "--combined_output",
        type=Path,
        default=None,
        help="Optional path for an extra combined training curve image."
    )
    return parser.parse_args()


def parse_bool(value):
    return str(value).strip().lower() in {"1", "true", "yes"}


def read_history(path):
    if not path.exists():
        raise FileNotFoundError(
            f"Training history not found: {path}. Run train.py once to generate it."
        )

    rows = []
    with open(path, "r", encoding="utf-8") as file:
        reader = csv.DictReader(file)
        for row in reader:
            rows.append({
                "epoch": int(row["epoch"]),
                "train_loss": float(row["train_loss"]),
                "train_acc": float(row["train_acc"]),
                "val_loss": float(row["val_loss"]),
                "val_acc": float(row["val_acc"]),
                "learning_rate": float(row["learning_rate"]),
                "is_best": parse_bool(row["is_best"]),
            })

    if not rows:
        raise ValueError(f"No training rows found in: {path}")

    return rows


def mark_best_epochs(axis, history):
    best_epochs = [row["epoch"] for row in history if row["is_best"]]
    for epoch in best_epochs:
        axis.axvline(epoch, color="tab:green", alpha=0.2, linewidth=2)


def plot_metric(history, output_path, title, y_label, series):
    epochs = [row["epoch"] for row in history]

    fig, ax = plt.subplots(figsize=(8.5, 5))
    for label, key in series:
        values = [row[key] for row in history]
        ax.plot(epochs, values, marker="o", label=label)

    mark_best_epochs(ax, history)
    ax.set_title(title)
    ax.set_xlabel("Epoch")
    ax.set_ylabel(y_label)
    ax.grid(alpha=0.25)
    ax.legend()
    fig.tight_layout()
    fig.savefig(output_path, dpi=180)
    plt.close(fig)


def plot_combined(history, output_path):
    epochs = [row["epoch"] for row in history]

    fig, axes = plt.subplots(1, 3, figsize=(16, 4.8))

    axes[0].plot(epochs, [row["train_loss"] for row in history], marker="o", label="Train Loss")
    axes[0].plot(epochs, [row["val_loss"] for row in history], marker="o", label="Val Loss")
    axes[0].set_title("Loss")
    axes[0].set_xlabel("Epoch")
    axes[0].set_ylabel("Loss")
    axes[0].grid(alpha=0.25)
    axes[0].legend()

    axes[1].plot(epochs, [row["train_acc"] for row in history], marker="o", label="Train Acc")
    axes[1].plot(epochs, [row["val_acc"] for row in history], marker="o", label="Val Acc")
    mark_best_epochs(axes[1], history)
    axes[1].set_title("Accuracy")
    axes[1].set_xlabel("Epoch")
    axes[1].set_ylabel("Accuracy")
    axes[1].set_ylim(0, 1.05)
    axes[1].grid(alpha=0.25)
    axes[1].legend()

    axes[2].plot(
        epochs,
        [row["learning_rate"] for row in history],
        marker="o",
        color="tab:purple",
    )
    axes[2].set_title("Learning Rate")
    axes[2].set_xlabel("Epoch")
    axes[2].set_ylabel("Learning Rate")
    axes[2].grid(alpha=0.25)

    fig.suptitle("Training History")
    fig.tight_layout()
    fig.savefig(output_path, dpi=180)
    plt.close(fig)


def main():
    args = parse_args()
    history = read_history(args.history)
    args.output_dir.mkdir(parents=True, exist_ok=True)

    plot_combined(history, args.output_dir / "training_curves_combined.png")
    if args.combined_output is not None:
        args.combined_output.parent.mkdir(parents=True, exist_ok=True)
        plot_combined(history, args.combined_output)
    plot_metric(
        history,
        args.output_dir / "training_loss_curve.png",
        "Training and Validation Loss",
        "Loss",
        [("Train Loss", "train_loss"), ("Val Loss", "val_loss")],
    )
    plot_metric(
        history,
        args.output_dir / "training_accuracy_curve.png",
        "Training and Validation Accuracy",
        "Accuracy",
        [("Train Acc", "train_acc"), ("Val Acc", "val_acc")],
    )
    plot_metric(
        history,
        args.output_dir / "learning_rate_curve.png",
        "Learning Rate Schedule",
        "Learning Rate",
        [("Learning Rate", "learning_rate")],
    )

    print(f"Saved training visualizations to {args.output_dir}")


if __name__ == "__main__":
    main()
